### ISSUE TITLE
IAM Authentication throws NameError on the good path

### ISSUE THREAD

**Issue by brackendawson** [sysdiglabs/sysdig-sdk-python#164]
I'm getting the following exception when authenticating with IAM:

```
Traceback (most recent call last):
  File "/home/jenkins/workspace/Containers-Registry/sync-sysdig-alerts/vaultfiles/scripts/sysdig/sync-alerts.py", line 29, in <module>
    source_client = create_sdcclient_for_instance(source_instance)
  File "/home/jenkins/workspace/Containers-Registry/sync-sysdig-alerts/vaultfiles/scripts/sysdig/sync-alerts.py", line 25, in create_sdcclient_for_instance
    ibm_headers = IbmAuthHelper.get_headers(url, api_key, guid)
  File "/usr/local/lib/python3.7/dist-packages/sdcclient/ibm_auth_helper.py", line 15, in get_headers
    iam_token = IbmAuthHelper.__get_iam_token(url, apikey)
  File "/usr/local/lib/python3.7/dist-packages/sdcclient/ibm_auth_helper.py", line 35, in __get_iam_token
    response = self.http.post(
NameError: name 'self' is not defined
```

It appears that this change tries to reference self in a static method: https://github.com/sysdiglabs/sysdig-sdk-python/pull/159/commits/2808518988f2e60aa41cbb8d1b8f536c386f62da#diff-d3358f2337a151eba234c36ba139abfa6a7a1175da19f9323488a6396afa13dcR35

**Comment by tembleking** [comment]
Hi @brackendawson thanks for pointing this out.
The PR #166 should fix this issue.
